my_scent_factory_blog:
    resource: "@MyScentFactoryBlogBundle/Resources/config/routing.yml"
    prefix:   /

my_scent_factory_ecommerce:
    resource: "@MyScentFactoryEcommerceBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
